### ISSUE TITLE
Program not working?

### ISSUE THREAD

**Issue by augis01** [cloutjs/ByeBye-Bitcoin#1]

**Comment by cloutjs** [comment]
please describe your problem more specifically

**Comment by augis01** [comment]
when i open it, it just closes

**Comment by cloutjs** [comment]
do you have python and the required packages installed?

**Comment by augis01** [comment]
i guess so...

**Comment by augis01** [comment]
oh, nvm had to reinstall python, working now, thx

**Comment by cloutjs** [comment]
well that is the only possible problem, mine is working fine
packages you need:
 - bs4 
 - time
 - os
 - requests

**Comment by cloutjs** [comment]
ah yea perfect, have fun!
