### ISSUE TITLE
Hi .. Js . Can I talk to you?? You have Tele?

### ISSUE THREAD

**Issue by Garyrogers30214** [cloutjs/ByeBye-Bitcoin#4]

**Comment by cloutjs** [comment]
@rcntly or clout#6250 on discord

**Comment by Garyrogers30214** [comment]
But I can't find you ? You have easier way I can reach you ? Pls . Tele is easiest or I could drop my discord

**Comment by Garyrogers30214** [comment]
Please..accept invite

**Comment by cloutjs** [comment]
didn't get anything yet

**Comment by Garyrogers30214** [comment]
Here sir .. Eddy Snegur#1906


Eddy Snegur#1906


I actually sent a friend request with this user iD on discord

**Comment by Garyrogers30214** [comment]
Ok .. I’m sorry . I’m asking if I could use it to work so I can get results

**Comment by cloutjs** [comment]
I know don't worry, we talked on discord so I closed this ticket since I think we don't need this anymore cause it's easier to talk on other platforms
